### ISSUE TITLE
Where the batcher_next_word is?

### ISSUE THREAD

**Issue by Jacklau9515** [SharmisthaJat/ACL2019-SimpleSentenceRepr-DNN-Brain#1]
Hi Sharmistha,

May I know where the 'batcher_next_word' is? From main_cuda.py, I noticed that you imported the 'batcher_next_word', but I cannot find it out through the entire project, so would you please provide the corresponding code for 'batcher_next_word'?

Many thanks,
Jack

**Comment by SharmisthaJat** [comment]
Hi Jack, 

Thanks for raising the issue. The file was missing from the repo. I have added it to the corresponding folders. Let me know if you face any other issue. 

Cheers,
Sharmistha
